services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: marsops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: se0509va
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"


  redis:
    image: redis:7
    ports:
      - "6379:6379"


  web:
    build: .
    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 MarsOps.asgi:application"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=marsops
      - DB_USER=postgres
      - DB_PASSWORD=se0509va
      - REDIS_HOST=redis
