# Generated by Django 6.0.3 on 2026-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_category_options_alter_resources_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='image_path',
            field=models.CharField(blank=True, help_text='Например: "img/products/pink_bag.jpg"', max_length=255, verbose_name='Путь к картинке'),
        ),
    ]
