# Generated by Django 6.0.3 on 2026-03-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0001_initial'),
        ('stations', '0002_alter_station_options_alter_station_crew_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitat',
            options={'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.RemoveField(
            model_name='habitat',
            name='habitat_type',
        ),
        migrations.AlterField(
            model_name='habitat',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название модуля'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitats', to='stations.station'),
        ),
    ]
