# Generated by Django 6.0.3 on 2026-03-11 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewmember',
            options={'verbose_name': 'Член экипажа', 'verbose_name_plural': 'Члены экипажа'},
        ),
        migrations.AlterModelOptions(
            name='crewskill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crewskill',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='crewskill',
            name='skill_name',
            field=models.CharField(max_length=100, verbose_name='Навык'),
        ),
    ]
