# Generated by Django 6.0.3 on 2026-03-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_stationreview_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationreview',
            name='author',
        ),
    ]
