# Generated by Django 6.0.3 on 2026-03-11 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mission_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='planned', max_length=100)),
                ('objective', models.TextField()),
                ('crew_members', models.ManyToManyField(related_name='missions', to='crew.crewmember')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='stations.station')),
            ],
        ),
    ]
