# Generated by Django 6.0.3 on 2026-03-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Миссия', 'verbose_name_plural': 'Миссии'},
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(max_length=100, verbose_name='Тип миссии'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название миссии'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='objective',
            field=models.TextField(verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(default='planned', max_length=100, verbose_name='Статус'),
        ),
    ]
