# Generated by Django 6.0.3 on 2026-03-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station_type', models.CharField(max_length=100)),
                ('established_date', models.DateField(auto_now_add=True)),
                ('crew_capacity', models.IntegerField(default=10)),
            ],
        ),
    ]
