# Generated by Django 6.0.3 on 2026-03-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
        migrations.AlterField(
            model_name='station',
            name='crew_capacity',
            field=models.IntegerField(default=10, verbose_name='Вместимость экипажа'),
        ),
        migrations.AlterField(
            model_name='station',
            name='established_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название станции'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(max_length=100, verbose_name='Тип станции'),
        ),
    ]
