# Generated by Django 6.0.3 on 2026-03-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_stationreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationreview',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stations.station'),
        ),
    ]
